# Generated by Django 4.2.1 on 2023-05-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='friendshiprequest',
            table=None,
        ),
    ]
