# Generated by Django 4.2.1 on 2023-05-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_alter_friendshiprequest_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='subscribed_on',
            new_name='subscriptions',
        ),
    ]
