# Generated by Django 4.2.1 on 2023-05-09 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OldRequest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OldRequest.from_person+', to=settings.AUTH_USER_MODEL)),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OldRequest.to_person+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
